-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 19:58:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(100) NOT NULL,
  `adreça` VARCHAR(100) NOT NULL,
  `codi postal` INT(5) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia_client` INT NOT NULL,
  `telefon` INT(12) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `provincia_client`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hamburguesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Begudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Begudes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  `Pizza_id` INT NOT NULL,
  `Hamburguesa_id` INT NOT NULL,
  `Beguda_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producte_Pizza1_idx` (`Pizza_id` ASC) VISIBLE,
  INDEX `Hamburguesa_id_idx` (`Hamburguesa_id` ASC) VISIBLE,
  INDEX `Beguda_id_idx` (`Beguda_id` ASC) VISIBLE,
  CONSTRAINT `Pizza_id`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `mydb`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Hamburguesa_id`
    FOREIGN KEY (`Hamburguesa_id`)
    REFERENCES `mydb`.`Hamburguesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Beguda_id`
    FOREIGN KEY (`Beguda_id`)
    REFERENCES `mydb`.`Begudes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`punt de venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`punt de venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detall_empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detall_empleat` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `funció` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telefon` INT(12) NOT NULL,
  `punt de venta_id` INT NOT NULL,
  `detall_empleat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleat_punt de venta1_idx` (`punt de venta_id` ASC) VISIBLE,
  INDEX `fk_empleat_detall_empleat1_idx` (`detall_empleat_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_punt de venta1`
    FOREIGN KEY (`punt de venta_id`)
    REFERENCES `mydb`.`punt de venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleat_detall_empleat1`
    FOREIGN KEY (`detall_empleat_id`)
    REFERENCES `mydb`.`detall_empleat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detall_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detall_entrega` (
  `id` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `empleat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detall_entrega_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  CONSTRAINT `fk_detall_entrega_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `mydb`.`empleat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `producte_id` INT NOT NULL,
  `detall_entrega_id` INT NOT NULL,
  `punt de venta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `detall_entrega_id`),
  INDEX `client_comanda_idx` (`client_id` ASC) VISIBLE,
  INDEX `producte_comanda_idx` (`producte_id` ASC) VISIBLE,
  INDEX `fk_comanda_detall_entrega1_idx` (`detall_entrega_id` ASC) VISIBLE,
  INDEX `fk_comanda_punt de venta1_idx` (`punt de venta_id` ASC) VISIBLE,
  CONSTRAINT `client_comanda`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producte_comanda`
    FOREIGN KEY (`producte_id`)
    REFERENCES `mydb`.`producte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_detall_entrega1`
    FOREIGN KEY (`detall_entrega_id`)
    REFERENCES `mydb`.`detall_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_punt de venta1`
    FOREIGN KEY (`punt de venta_id`)
    REFERENCES `mydb`.`punt de venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detall_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detall_comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data/hora` DATETIME NOT NULL,
  `botiga o delivery` VARCHAR(45) NOT NULL,
  `tipus producte/cantitat` VARCHAR(45) NOT NULL,
  `preu total` FLOAT NOT NULL,
  `detall_entrega_id` INT NOT NULL,
  `comanda_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detall_comanda_detall_entrega1_idx` (`detall_entrega_id` ASC) VISIBLE,
  INDEX `comanda_id_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_detall_comanda_detall_entrega1`
    FOREIGN KEY (`detall_entrega_id`)
    REFERENCES `mydb`.`detall_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comanda_id`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `mydb`.`comanda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localitat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `provincia_id`),
  INDEX `fk_localitat_provincia1_idx` (`provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_localitat_provincia1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `mydb`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipus_pizza` VARCHAR(45) NULL,
  `Pizza_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pizza_id`),
  INDEX `fk_Carta_Pizza1_idx` (`Pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carta_Pizza1`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `mydb`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
