-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 19:58:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user name` VARCHAR(45) NOT NULL,
  `gender` TINYTEXT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal code` INT(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Canal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descrpció` VARCHAR(100) NOT NULL,
  `creation_date` DATETIME(45) NOT NULL,
  `User_id` INT NOT NULL,
  `Videos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Canal_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Canal_Videos1_idx` (`Videos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Canal_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Canal_Videos1`
    FOREIGN KEY (`Videos_id`)
    REFERENCES `mydb`.`Videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estat Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estat Playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME(45) NOT NULL,
  `id_public` VARCHAR(45) NULL,
  `id_privat` VARCHAR(45) NULL,
  `Playlistcol` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  `Canal_id` INT NOT NULL,
  `Estat Playlist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Estat Playlist_id`),
  INDEX `fk_Playlist_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Playlist_Canal1_idx` (`Canal_id` ASC) VISIBLE,
  INDEX `fk_Playlist_Estat Playlist1_idx` (`Estat Playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_Canal1`
    FOREIGN KEY (`Canal_id`)
    REFERENCES `mydb`.`Canal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_Estat Playlist1`
    FOREIGN KEY (`Estat Playlist_id`)
    REFERENCES `mydb`.`Estat Playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estat Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estat Video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripció` VARCHAR(100) NOT NULL,
  `tamany` VARCHAR(5) NOT NULL,
  `nom arxiu` VARCHAR(20) NOT NULL,
  `durada` VARCHAR(5) NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `num reproduccions` INT NOT NULL,
  `num likes` INT NOT NULL,
  `num dislikes` INT NOT NULL,
  `User_id` INT NOT NULL,
  `Playlist_id` INT NOT NULL,
  `Estat Video_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Estat Video_id`),
  INDEX `fk_Videos_User_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Videos_Playlist1_idx` (`Playlist_id` ASC) VISIBLE,
  INDEX `fk_Videos_Estat Video1_idx` (`Estat Video_id` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_Playlist1`
    FOREIGN KEY (`Playlist_id`)
    REFERENCES `mydb`.`Playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_Estat Video1`
    FOREIGN KEY (`Estat Video_id`)
    REFERENCES `mydb`.`Estat Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentaris` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(120) NOT NULL,
  `creation_date` DATETIME(45) NOT NULL,
  `Videos_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comentaris_Videos1_idx` (`Videos_id` ASC) VISIBLE,
  INDEX `fk_Comentaris_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comentaris_Videos1`
    FOREIGN KEY (`Videos_id`)
    REFERENCES `mydb`.`Videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentaris_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
